package com.emitrom.ti4j.mobile.modules.facebook.client;

import com.emitrom.ti4j.mobile.client.core.events.TiEvent;
import com.google.gwt.core.client.JavaScriptObject;

public class FBLoginEvent extends TiEvent {

    protected FBLoginEvent(JavaScriptObject obj) {
        jsObj = obj;
    }

    /**
     * Indicates if the user canceled the login request by closing the dialog.
     */
    public native boolean isCanceled() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		return jso.canceled;
    }-*/;

    /**
     * Error code. Error code will be 0 if success is true, nonzero otherwise.
     * If the error was generated by the operating system, that system's error
     * value is used. Otherwise, this value will be -1
     */
    public native int getCode() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		return jso.code;
    }-*/;

    /**
     * Data returned by Facebook when we query for the UID (using graph path
     * "me") after a successful login. Data is in JSON format, and includes
     * information such as user name, locale and gender.
     */
    public native FBData getData() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		var obj = jso.data;
		return @com.emitrom.ti4j.mobile.modules.facebook.client.FBData::new(Lcom/google/gwt/core/client/JavaScriptObject;)(obj);
    }-*/;

    /**
     * Error message, if any returned. Will be undefined if success is true.
     */
    public native String getError() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		return jso.error;
    }-*/;

    /**
     * Indicates if the user was logged in successfully. Returns true if request
     * succeeded, false otherwise.
     */
    public native boolean isSuccess() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		return jso.success;
    }-*/;

    /**
     * User ID returned by Facebook if the login was successful.
     */
    public native String getUid() /*-{
		var jso = this.@com.emitrom.ti4j.core.client.ProxyObject::getJsObj()();
		return jso.uid;
    }-*/;
}
